name: Build and deploy APK

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Fetch master branch
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Decode google-services.json
        env:
          GOOGLE_SERVICES: ${{ secrets.GOOGLE_SERVICES }}
        run: echo $GOOGLE_SERVICES > app/google-services.json

      - name: Build Release APK
        run: ./gradlew clean assembleRelease

      - name: Rename APK file
        run: cd app/build/outputs/apk/release && mv app-release-unsigned.apk LBMeals.apk

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: lb-meals-apk
          path: 'app/build/outputs/apk/release/LBMeals.apk'
