name: Code Style Validation

on: pull_request

jobs:
  code_style:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Validate Code Style
        run: ./gradlew clean ktlintCheck --no-daemon

      - name: Upload KtLint Reports
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: "ktlint-reports"
          path: "app/build/reports/ktlint/"
