name: Test Coverage Verification

on: pull_request

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Decode google-services.json
        env:
          GOOGLE_SERVICES: ${{ secrets.GOOGLE_SERVICES }}
        run: echo $GOOGLE_SERVICES > app/google-services.json

      - name: Build Project
        run: ./gradlew assemble

      - name: Test Coverage Verification
        run: ./gradlew jacocoTestCoverageVerification

      - name: Create Coverage Report
        run: ./gradlew jacocoCoverageReport
